### ISSUE TITLE
OF 0.9.x update?

### ISSUE THREAD

**Issue by antimodular** [timknapen/ofxSURFTracker#1]
hi
your addon looks very interesting.
any plans to update it to OF 0.9.x?

**Comment by timknapen** [comment]
yes, sure!
I'll take a look at it soon.

**Comment by timknapen** [comment]
hmm looks like a lot changed in opencv2... I'll see if I can work around it.

**Comment by timknapen** [comment]
Ok, never mind. Some files have moved around and some code was changed in openCV, but everything seems to be working after a minor fix.
Everything should be fine for 090 to 093 now.

**Comment by antimodular** [comment]
great thanks.
